default_session = "default"
display_full_path = true
excluded_dirs = [
  "ds",
  "foss",
  "ai3-react-native",
  "TNI",
  "node_modules",
  ".venv",
  "target",
  ".elixir_ls",
  "_build",
  "deps",
  ".git",
  "dist",
  "assets",
  "public",
  "vendor",
  ".sass-cache",
  "wp-content",
  "tmp",
  "cache",
  ".next",
  ".vinxi",
  ".output",
  ".react-router",
  ".expo",
  "tools",
  "Xcode",
  "databases",
  "zig-cache",
  ".terraform",
  "gopkg.in",
  "cloud.google.com",
  "cache",
  "go.opentelemetry.io",
  "google.golang.org",
  "mod",
  "pkg",
  "__MACOSX",
  ".config",
  "app-release",
  "runtime",
  "build",
  "components",
  ".idea",
  ".gradle",
  "priv",
  "java"
]

[[search_dirs]]
path = "/path/to/projects"
depth = 10
